### ISSUE TITLE
Integrate CI builds

### ISSUE THREAD

**Issue by rasendubi** [mar9000/ecmascript4mps#13]
We could leverage Travis CI to automatically run all tests and ensure that language and example solutions always build.

**Comment by mar9000** [comment]
Hi @rasendubi I've granted you push access to the repository. Check if it is enough to setup github to run CI builds.

**Comment by rasendubi** [comment]
Owner permission is required to activate travis for a repository: https://docs.travis-ci.com/user/tutorial/#prerequisites

```
Prerequisites

To start using Travis CI, make sure you have:

-  A GitHub account.
-  Owner permissions for a project hosted on GitHub.
```

I think you can sign up for Travis and activate the repository. That should be enough for Travis to pick up the job when I push `.travis.yaml`.

**Comment by mar9000** [comment]
The configuration added by @rasendubi worked perfectly and the first build of development passed successfully.
