### ISSUE TITLE
Complete the implementation of class fields, private methods and decorators.

### ISSUE THREAD

**Issue by mar9000** [mar9000/ecmascript4mps#7]
Reference documents:
- https://tc39.github.io/proposal-class-fields
- https://tc39.github.io/proposal-private-methods  
  https://2ality.com/2019/07/private-methods-accessors-in-classes.html
- https://tc39.es/proposal-decorators/#sec-syntax

## Class fields implementation

- a migration transforms the `JSIdentifier` of `JSMemberExpression` in `JSIdentifierName` because reserved words are permitted as internal fields name like `myObject.function`.  
  The migration has also an associated test.

- add `JSPrivateIdentifier` that extends `JSIdentifierName`:
  ```ebnf
  PrivateIdentifier::
    # IdentifierName
  ```
  It extends JSIdentifierName and has a different editor.

- add `ClassElementName`:
  ```ebnf
  ClassElementName[Yield, Await]:
    PropertyName[?Yield, ?Await]
    PrivateIdentifier
  ```
  It is an interface extended by `JSIPropertyName` and the new interface `JSIPrivateIdentifier`.

- add `FieldDefinition`:
  ```ebnf
  FieldDefinition[Yield, Await]:
    ClassElementName[?Yield, ?Await]   Initializer[In, ~Yield, ~Await]opt
  ```
  It's a concept, it implements the three interfaces to pass the parameters to the initializer.

- add an alternative to `ClassElement`:
  ```ebnf
  ClassElement[Yield, Await]:
    FieldDefinition[?Yield, ?Await];
  ```
  `JSFieldDefinition` implements the interface `JSIClassElement`.

- add an alternative to `MemberExpression`:
  ```ebnf
  MemberExpression[Yield, Await]:
    MemberExpression[?Yield, ?Await].PrivateIdentifier
  ```
  * `MemberExpression` alternatives have `MemberExpression` to the left, actually we have `object: JSPrimaryExpression[1]` so this os going to be changed in `object: JSAbstractMemberExpression[1]`. No migration required because we substitute with a subconcept.
  * on the right actually we can have `JSIdentifier` and it's not correct: the grammar has `IdentifierName` that allows also reserved words, infact `myVar.for` is permitted. **A migration is required**. We also need an interface grouping JSIIdentifierName and `JSPrivateIdentifierReference`, private identifier must be declared before used.

- private fields scope is implemented with:

  * `JSClassDeclaration` now implements `ScopeProvider`.
  * `JSIClassElement` extends `JSBindingProvider` so `JSFieldDefinition` can override the implementation.

- the following alternative to `CallExpression` **is not needed**:
  ```ebnf
  CallExpression[Yield, Await]:
    CallExpression[?Yield, ?Await].PrivateIdentifier
  ```

- tests:

  - for private fields scope.
  - for construction of `this.#privateField.field`.
  - for construction of `this.field.field`.

- examples for private fields and member expression of a member expression (this.a.a).

## Private methods implementation

This implementation provides:

```javascript
class MyClass {
  #privateOrdinaryMethod() {}
  // async, generator private methods will be implemented contextually to async, generator etc
  // * #privateGeneratorMethod() {}
  // set/get #privateGetSet() {}
}
```

The grammar is:
```ebnf
MethodDefinition[Yield, Await]:
  PropertyName[?Yield, ?Await](UniqueFormalParameters[~Yield, ~Await]){FunctionBody[~Yield, ~Await]}   <-- from
  ClassElementName[?Yield, ?Await](UniqueFormalParameters[~Yield, ~Await]){FunctionBody[~Yield, ~Await]}   <-- to
```

* change `methodName : JSIPropertyName[1]` to `methodName : JSIClassElementName[1]` in `JSMethodDefinition`, no migration required.

* let `JSMethodDefinition` overrides `JSBindingProvider` to provides scope for its private identifier if present.

## Decorators implementation

This was already partially implemented. What we are missing is:

* for the alternative `( Expression[+In] )` of `DecoratorMamberExpression` I've added `HasIn` to `JSParenExpressionDecorator`.

* `JSClassElement` should extend `JSIDecoratorList` so methods and fields can be decorated (`JSClassDeclaration` is already this way).

* `JSClassExpression` should extend `JSIDecoratorList`, the concept is present but not yet used.

**Comment by rasendubi** [comment]
I'm getting the following error on the current `development` branch when compiling `all-examples`:

```
// More on decorators, part of issue #7.
var deco1;

@deco1
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSParenExpressionDecorator'!>
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSDotMemberExpressioDecorator'!>
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSDotMemberExpressioDecorator'!>
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSDotMemberExpressioDecorator'!>
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSDotMemberExpressioDecorator'!>
@deco1(1)
@<!TextGen not found for 'org.mar9000.mps.ecmascript.structure.JSDotMemberExpressioDecorator'!>(3)
class ForDecorators {
  field1 = 4
  ;
  method1() {
  }
  constructor__() {
  }
}
```

**Comment by mar9000** [comment]
Fixed adding two missing TextGen concepts.
